### PR TITLE
Updated sending of notifications

### LINKED ISSUE #26: Cron questions/issues
A few notes about the cron:
- When the plugin is installed but not active, does the cron still run? Should a check in the beginning of cron.php check whether the plugin is active, and otherwise directly quit?
- When no certificates are renewed, should a message still be sent? Or perhaps with a different header? Or add the number of renewals in the subject header?
- 2 messages in my case 2 tickets were merged together; see image:

image

### PR DESCRIPTION
**Pull request by Wouter0100**
We're now using a new feature in DA 1.49.2 and up. See https://www.directadmin.com/features.php?id=1829 for more information. 

This PR fixes #26.

### CODE REVIEW

**Comment by zenire** [comment]
Nice to see DirectAdmin added this function. Since this is a more reliable function we will use this function.

**Comment by barryvdh** [comment]
This is not actually released yet, is it? I don't see it on http://www.directadmin.com/versions.php
What happens when you run this on and older DirectAdmin versions?

**Comment by Wouter0100** [comment]
Then you won't receive a notification. It's isn't released yet indeed (but, it's in the pre-release binaries), just like this plugin isn't released yet.  It won't break the cron.

To test this feature you must upgrade to pre-release V1.49.2.

**Comment by zenire** [comment]
If you run an older version of DirectAdmin you will not receive a notification. Since we have an alpha/beta currently we assume it would not be a problem to get pre-release binaries from DirectAdmin: http://help.directadmin.com/item.php?id=408

**Comment by Wouter0100** [comment]
And; I don't think the current workaround was really a option. It was nasty, non-functional (you didn't receive a notification in your email when you said so to DirectAdmin) and buggy. It would be better to just not send a notification when your version isn't supported, then something that may break a message in DirectAdmin.

**Comment by barryvdh** [comment]
Can't you also ask him to add some way to add certificates during a cron? ;)

**Comment by Wouter0100** [comment]
Hmm, I'm currently working on doing everything through the API (#35), so I don't think that's necessary? :smile:

**Comment by barryvdh** [comment]
Oh cool, I thought that wasn't really viable with the login keys etc, but glad that's possible :)

**Pull request merged**
