### PR TITLE
Require login keys and always use API

### PR DESCRIPTION
**Pull request by Wouter0100**
This PR is for all the work done to fully move to the API where login keys are required.

WIP - Do not merge.

### CODE REVIEW

**Comment by Wouter0100** [comment]
I've added /CMD_API_LOGIN_KEYS to the required permission list, because we may need to upgrade the login key in the future (give more permissions). On this way we can automate this when a stable is released. :smile:

**Comment by barryvdh** [comment]
This will lead to possible elevation of rights x because you can create a key with all the rights.
So once it's stable, you should probably remove it..

**Comment by Wouter0100** [comment]
Hmm, good point. But when we did, we're even unable to update it, since the /CMD_API_LOGIN_KEYS requires the current password.

**Comment by barryvdh** [comment]
Can't you use the loginkey as current password?

**Comment by Wouter0100** [comment]
For upgrading? Hmm, I'm not sure, but I've removed the API LOGIN KEYS permission.

**Pull request closed without merging**
