### PR TITLE
Empty array if no subdomains are selected.

### PR DESCRIPTION
**Pull request by sjerdo**
Fixes issue #40

### CODE REVIEW

**Comment by sjerdo** [comment]
@Wouter0100 Why is the config changed to include all subdomains [here](https://github.com/petertjuh360/da-letsencrypt/blob/master/scripts/cron.php#L90)?

**Comment by zenire** [comment]
Thank you!

**Comment by Wouter0100** [comment]
@sjerdo To reissue it in the cron. Else we don't have a clue which subdomains are selected when reissuing.

**Comment by sjerdo** [comment]
@Wouter0100 Are you sure? In [line 81](https://github.com/petertjuh360/da-letsencrypt/blob/master/scripts/cron.php#L81) the subdomains are fetched from the config and included in the CSR. Seems correct. But, in [line 90](https://github.com/petertjuh360/da-letsencrypt/blob/master/scripts/cron.php#L90) you set the subdomains in config to all the subdomains for the domain (so not just the ones selected). So next time the cron will run, it'll try to include all the subdomains in the certificate.

I'll post this comment also in issue #26. Let's move the conversation there.

**Pull request merged**
