### PR TITLE
Catch exception for more information

### PR DESCRIPTION
**Pull request by barryvdh**
Show which domain is failing, for example when DNS cannot be resolved. This way, it's more obvious where the problem lies.

### CODE REVIEW

**Comment by barryvdh** [comment]
Updated 2 more cases.

Ideally the AcmeException would be more useful, now it has the json body inside the message, while for 4xx errors with json data, it could be converted to a proper error message.

**Comment by Wouter0100** [comment]
Hmm, thanks! Can't we convert back to plain text the AcmeException in some way?

**Comment by barryvdh** [comment]
We're using a fork anyways, so we could just fix the library.

**Comment by barryvdh** [comment]
Opened issue upstream; https://github.com/kelunik/acme/issues/4

**Comment by kelunik** [comment]
You should no longer need the fork, the library should be PHP 5.5 compatible now.

**Comment by Wouter0100** [comment]
Whow! Thanks, @kelunik. I'll update the composer asap

**Comment by kelunik** [comment]
Note that you should use `Amp\wait($acme->...)` then, I didn't remove the async part as you did.

**Comment by Wouter0100** [comment]
Ah, okay, I'll update that. Should be fine :+1:

**Comment by barryvdh** [comment]
Regardless of the upstream issue, this could probably already be merged for clearer errors.

**Comment by Wouter0100** [comment]
Indeed. Thanks.

**Pull request merged**
